In [9]:
from numpy import *
a = array([1,3,4,5,6,6])
b = [1,2,3,4,5,7]
c = array(b)
print(a+c,a+b)
d = [1,2,3,4,6,7]
print(b+d)

[ 2  5  7  9 11 13] [ 2  5  7  9 11 13]
[1, 2, 3, 4, 5, 7, 1, 2, 3, 4, 6, 7]


In [4]:
import numpy as np
np.__version__
np.show_config()

blas_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Users/Aman.py/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Aman.py/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Users/Aman.py/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Aman.py/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Users/Aman.py/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Aman.py/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_core_dll', 'mkl_intel_lp64_dll', 'mkl_intel_thread_dll']
    library_dirs = ['C:/Us

In [5]:
z = np.zeros(10)
z[4] = 1
z

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [2]:
a=np.arange(10,49)

In [3]:
a.reshape(3,13)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]])

In [28]:
#find indices of non zero elements
a = np.array([0,1,0,2,0,3,0,4,0,5,0,6,0,7,0,8,0,9,0])
a.nonzero()

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17], dtype=int64),)

In [6]:
#create a 3*3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [7]:
np.random.random((3,3,3))

array([[[ 0.67982401,  0.8223785 ,  0.0055537 ],
        [ 0.23652196,  0.22924032,  0.388885  ],
        [ 0.31424889,  0.55171185,  0.7982735 ]],

       [[ 0.13518671,  0.89798038,  0.87549768],
        [ 0.05242976,  0.77873135,  0.6251368 ],
        [ 0.4886811 ,  0.6077442 ,  0.75041099]],

       [[ 0.27628568,  0.44094524,  0.65912403],
        [ 0.21409996,  0.26134735,  0.40550013],
        [ 0.63251752,  0.14197847,  0.1661913 ]]])

In [44]:
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [2]:
a = {1:'aman',2:'hello',3:'python'}
b = {1:'agarwal',2:'world',3:'language'}
a[1] = a[1],b[1]
a[2] = a[2],b[2]
a[3] = a[3],b[3]
print(a)

{1: ('aman', 'agarwal'), 2: ('hello', 'world'), 3: ('python', 'language')}


In [21]:
import numpy as np
t1 = np.array(np.arange(0.0,5.0,0.005))
t2 = np.arange(0.0,5.0,0.009,dtype=int)
print(type(t1))
print(type(t2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [78]:
#Array
from numpy import *
arr = array(range(0,10,1),float)
arr=arr.reshape([2,5])
print(arr)
print(arr.shape)
b=arr
c=arr.copy()
b[0]=1
print(b);print(c);print(b.tolist());print(list(b));print(b.tobytes());s=b.tostring();print(s);s=fromstring(s);print(s);
print(arr.transpose());print(c.transpose());print(arr.flatten());con_cat=concatenate((arr,b,c),axis=0);print(con_cat)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]
(2, 5)
[[ 1.  1.  1.  1.  1.]
 [ 5.  6.  7.  8.  9.]]
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]
[[1.0, 1.0, 1.0, 1.0, 1.0], [5.0, 6.0, 7.0, 8.0, 9.0]]
[array([ 1.,  1.,  1.,  1.,  1.]), array([ 5.,  6.,  7.,  8.,  9.])]
b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x00\x00\x00\x00\x00\x00\x1c@\x00\x00\x00\x00\x00\x00 @\x00\x00\x00\x00\x00\x00"@'
b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x00\x00\x00\x00\x00\x00\x1c@\x00\x00\x00\x00\x00\x00 @\x00\x00\x00\x00\x00\x00"@'
[ 1.  1.  1.  1.  1.  5.  6.  7.  8.  9.]
[[ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 1.  9.]]
[[ 0.  5.]
 [ 1.  6.]
 [ 2.  7.]
 [ 3.  8.]
 [ 4.  9.]

In [96]:
#other ways to create an array
ar=arange(1,100,5)
ar_1=ones((4,4),dtype=bool)
print(ar);print(ar_1);print(zeros((2,3)));print(ones_like(con_cat));print(zeros_like(con_cat));print(identity(3,tuple));print(eye(5,k=0))

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [103]:
#Array Mathematics
arr_a = arange(1,100,5)
arr_b = arange(100,1,-5)
print(array(arr_a+arr_b),array(arr_a-arr_b),array(arr_a*arr_b),array(arr_a/arr_b),array(arr_a%arr_b),array(arr_a//arr_b),array(arr_a**arr_b))
print(sqrt(arr_a))

[101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101
 101 101] [-99 -89 -79 -69 -59 -49 -39 -29 -19  -9   1  11  21  31  41  51  61  71
  81  91] [ 100  570  990 1360 1680 1950 2170 2340 2460 2530 2550 2520 2440 2310 2130
 1900 1620 1290  910  480] [  1.00000000e-02   6.31578947e-02   1.22222222e-01   1.88235294e-01
   2.62500000e-01   3.46666667e-01   4.42857143e-01   5.53846154e-01
   6.83333333e-01   8.36363636e-01   1.02000000e+00   1.24444444e+00
   1.52500000e+00   1.88571429e+00   2.36666667e+00   3.04000000e+00
   4.05000000e+00   5.73333333e+00   9.10000000e+00   1.92000000e+01] [ 1  6 11 16 21 26 31 36 41 46  1 11 21 31 11  1  1 11  1  1] [ 0  0  0  0  0  0  0  0  0  0  1  1  1  1  2  3  4  5  9 19] [          1           0 -2122534759           0  1379313601           0
  -483675327           0  1242261473           0   835684585           0
  1828862497           0  -818857903           0 -1669737407  1885437952
   270703673  -436207616]


TypeError: ufunc 'sqrt' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''

In [106]:
arr_c = arange(1,100,.1)
print(arr_c);print(floor(arr_c));print(ceil(arr_c));print(rint(arr_c))

[  1.    1.1   1.2   1.3   1.4   1.5   1.6   1.7   1.8   1.9   2.    2.1
   2.2   2.3   2.4   2.5   2.6   2.7   2.8   2.9   3.    3.1   3.2   3.3
   3.4   3.5   3.6   3.7   3.8   3.9   4.    4.1   4.2   4.3   4.4   4.5
   4.6   4.7   4.8   4.9   5.    5.1   5.2   5.3   5.4   5.5   5.6   5.7
   5.8   5.9   6.    6.1   6.2   6.3   6.4   6.5   6.6   6.7   6.8   6.9
   7.    7.1   7.2   7.3   7.4   7.5   7.6   7.7   7.8   7.9   8.    8.1
   8.2   8.3   8.4   8.5   8.6   8.7   8.8   8.9   9.    9.1   9.2   9.3
   9.4   9.5   9.6   9.7   9.8   9.9  10.   10.1  10.2  10.3  10.4  10.5
  10.6  10.7  10.8  10.9  11.   11.1  11.2  11.3  11.4  11.5  11.6  11.7
  11.8  11.9  12.   12.1  12.2  12.3  12.4  12.5  12.6  12.7  12.8  12.9
  13.   13.1  13.2  13.3  13.4  13.5  13.6  13.7  13.8  13.9  14.   14.1
  14.2  14.3  14.4  14.5  14.6  14.7  14.8  14.9  15.   15.1  15.2  15.3
  15.4  15.5  15.6  15.7  15.8  15.9  16.   16.1  16.2  16.3  16.4  16.5
  16.6  16.7  16.8  16.9  17.   17.1  17.2  17.3  1

In [128]:
arr_d = array([[1,2],[3,4],[5,6],[7,8],[9,10]])
for (x,y) in arr_d:
    print(x**y)
print(arr_c.argmax(),arr_c.argmin())
print(arr_d.min(axis=0),arr_d.min(axis=1))
sorted(arr_c)
print(arr_d.sort(axis=0));arr_e=arr_c.clip(0,5);print(arr_c.clip(0,5));print(unique(arr_e));
print(arr_d.diagonal(axis1=0,axis2=1))

1
81
15625
5764801
-808182895
989 0
[1 2] [1 3 5 7 9]
None
[ 1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4
  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9
  4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.   5.   5.   5.
  5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.
  5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.
  5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.
  5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.
  5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.
  5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.
  5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.
  5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.
  5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.   5.
  5.   5.   5.   5.   5.   5.   5.   5.

In [138]:
#Comparison operators and value testing
ar_a = array([1,4,7]);ar_b = array([0,5,9])
ar_c=ar_a > ar_b;ar_d = ar_b<10;
ar_e = 0<ar_a<4
print(any(ar_d),all(ar_d));
print(ar_e)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [139]:
x = ["B", "D", "Z", "A", "E", "Q"]
print(x[-5:])

['D', 'Z', 'A', 'E', 'Q']


In [140]:
import numpy as np
np_2d = np.array([[4, 5, 6], 
                  [17, 18, 19]])
print(np_2d[1:, :1])

[[17]]


In [141]:
x = "there are eight planets in our solar system"
print(x.capitalize())

There are eight planets in our solar system


In [142]:
import numpy as np
x = np.array([4, 4, 7, 7, 5, 5, 7, 4])
y = np.array([1, 6, 2, 8, 7, 5, 0, 3])
print(corrcoef(x, y))

[[ 1.        -0.0693167]
 [-0.0693167  1.       ]]


In [143]:
x = 0.89
y = "x is:"
print(y + (str(x)))

x is:0.89


In [146]:
y = [1, 2, "A" + "!"]
a = ["A", "B" * 2, "C"]

In [147]:
y,a

([1, 2, 'A!'], ['A', 'BB', 'C'])

In [148]:
import numpy as np
x = np.array([1, 2, True, False, 3])
print(x)

[1 2 1 0 3]


In [149]:
import numpy as np
x = np.array([1, 2, True, False, "3"])
print(x)

['1' '2' 'True' 'False' '3']


In [151]:
p = ["a", 1, "b", 3, "c", 4]
q = p.extend(['Z',10])
print(q)

None


In [152]:
import numpy as np
x = np.array([6, 4, 2])
y = np.array([2, True, False])
print(x / y)

[  3.   4.  inf]


C:\Users\Aman.py\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


In [153]:
4%3

1

In [154]:
x = False
if x % 2 == 0:
    print("First attempt")
elif x % 3 == 0:
    print("Second attempt")
else:
    print("Final attempt")

First attempt


In [155]:
x = 1
if not x:
    print("First attempt")
elif x % 2 == 0:
    print("Second attempt")
else:
    print("Final attempt")

Final attempt


In [156]:
1%2

1